version: '3.8'
services:
  rails:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 1234:3000
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
    depends_on:
      - db

  db:
    image: postgres:12.2
    env_file:
      - ./.env
    volumes:
      - search-db:/var/lib/postgresql/data

  webpacker:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: bash -c "yarn && ./bin/webpack-dev-server"
    ports:
      - 3035:3035
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    depends_on:
      - rails

volumes:
  search-db:
