kind: PersistentVolume
apiVersion: v1
metadata:
  name: test-search-db-volume
  namespace: test-search
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /srv/k8s/dbs/test-search
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker-1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-search-db-claim
  namespace: test-search
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
