apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: search-fbandrey-cert
  namespace: test-search
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - 'test-search.fbandrey.com'
  issuerRef:
    name: le-http-prod
    kind: ClusterIssuer
  secretName: search-fbandrey-tls
  privateKey:
    rotationPolicy: Always
